### ISSUE TITLE
{% image %} is not working

### ISSUE THREAD

**Issue by haroldao** [prismicio-community/eleventy-plugin-prismic#9]
It's me again 😅...

For `{% image %}`

When I want to run my local server I have this error :
![image](https://user-images.githubusercontent.com/36776278/158158492-e329e31f-9add-439d-93e0-f5904b0951f1.png)

So at the end the server stopped:
![image](https://user-images.githubusercontent.com/36776278/158158685-3c02a195-ef58-4443-b254-dfb6972c4136.png)

To temporary avoid this issue on my local server, I have to comment all `{% image  ......%}`, then the local server will work and my images will be rendered but I'll still have the same error between each saving after I uncommented the images.
![image](https://user-images.githubusercontent.com/36776278/158159372-ca6b4b72-a642-451f-93d0-f6db883ecec9.png)
![image](https://user-images.githubusercontent.com/36776278/158159511-5152b75f-037c-433f-8f4e-6c87fef2e6f2.png)
![image](https://user-images.githubusercontent.com/36776278/158159733-6094d6e8-5e04-40d1-b023-3b34f4fc7e11.png)
![image](https://user-images.githubusercontent.com/36776278/158160966-3a9a1498-b83b-43f3-8afb-97b7c9f865ae.png)

Btw... I also have this error on Netlify which make all my images are not visible.

**Comment by haroldao** [comment]
Here's the output of `{{ document.data.footer_logo | json }}`

`{"dimensions":{"width":1331,"height":313},"alt":"Trafik Plus logo","copyright":null,"url":"https://trafik-plus.cdn.prismic.io/trafik-plus/ddccb391-ec65-4d4c-87da-53bb964808f2_Trafik_Plus_Logo_2.svg"}`

**Comment by haroldao** [comment]
Something weird I saw was that the code base in the repo is different from mine.
The plugin uses the latest version tho.....

![image](https://user-images.githubusercontent.com/36776278/158166567-a46269f5-ca47-48aa-ad58-90f3c4a3a2e6.png)
![image](https://user-images.githubusercontent.com/36776278/158166573-42ca4fc7-696b-4c2c-b4a4-bb3d6d627a76.png)

**Comment by lihbr** [comment]
Hey there, thank you so much for reporting an issue again!

I don't really see what's going wrong here 🤔

- Can you try to provide a minimal reproduction of the issue so I can try troubleshooting it from there?
- Are you experiencing the issue with other shortcodes?

Looking at the screenshots, my hunch goes toward a failure because `document.data.footer_logo` is not always your "layout" document in Prismic. Could you perhaps try with `{% image prismic.layout.en-us.data.footer_logo %}` (or with `{% image prismic.layout.en-us[0].data.footer_logo %}` if an array)

**Comment by haroldao** [comment]
- everytime I use `{% image XXXXXX %}`, I have this issue. If I have`{% image XXXXXX %}` while the server is running, the image is shown but I have the error message in the terminal. If I decide to turn down the local server and decide the run it again, It will crash and I'll not be able to run everything (my temporary solution is to comment all `{% image XXXXXX %}` before running the local server and uncomment everything when the local server is on)

- Not for now. I only used asText, asHTML, (image)

Ohhh sorry I forgot to share the beginning of my file :
![image](https://user-images.githubusercontent.com/36776278/158231482-55029d4b-8d97-4014-936b-fd2d2d622346.png)

(that's why I use 'document'😅)
----

Btw... your 2 other solutions are not working :/

**Comment by haroldao** [comment]
Here's my JSON when I do `{{ prismic.layout | json }}`

https://jsoneditoronline.org/#left=cloud.50fe064f243c4fa19cc960eea7ea04d1 (make sure to click 'Copy >')

**Comment by haroldao** [comment]
One more thing 😅 I don't know why all data from Prismic are not rendered in the 404 page :/
![image](https://user-images.githubusercontent.com/36776278/158233857-52322347-b3bf-44ee-862f-38349fd9ae64.png)

**Comment by lihbr** [comment]
OK, yeah, that looks weird to me! I'll need a minimal reproduction to troubleshoot forward/understand the issue better.

Can you:
- Bootstrap a new 11ty project with Prismic ;
- Replicate the scenario leading to the above issue (you can use your existing Prismic repository for the data, don't worry);
- Share this minimal project here (you can upload zip here, if so do it without the `node_modules` folder);
- Explain how with that minimal project how you're experiencing an issue.

Without a reproduction or access to a project, it's extremely hard to guess what is/could go wrong and provide adequate support :/

Thanks for your collaboration!

**Comment by lihbr** [comment]
Closing this as it became stale, feel free to reopen it if you want to continue investigating the issue!

**Comment by haroldao** [comment]
> OK, yeah, that looks weird to me! I'll need a minimal reproduction to troubleshoot forward/understand the issue better.
> 
> Can you:
> 
> * Bootstrap a new 11ty project with Prismic ;
> * Replicate the scenario leading to the above issue (you can use your existing Prismic repository for the data, don't worry);
> * Share this minimal project here (you can upload zip here, if so do it without the `node_modules` folder);
> * Explain how with that minimal project how you're experiencing an issue.
> 
> Without a reproduction or access to a project, it's extremely hard to guess what is/could go wrong and provide adequate support :/
> 
> Thanks for your collaboration!
[eleventy-base-blog.zip](https://github.com/prismicio-community/eleventy-plugin-prismic/files/9185162/eleventy-base-blog.zip)

Here's a ZIP folder. I used the starter from Eleventy (called Base Blog). And I replicate the issue with the image (still not working too) :) + I tried your code for the [language switcher ](https://github.com/prismicio-community/eleventy-plugin-prismic/issues/11)and same thing (with link/endlink)

**Comment by haroldao** [comment]
I only added new lines of code in `.eleventy.js` and in `base.njk`

**Comment by haroldao** [comment]
Here's the error outputted in the terminal for the "link/endlink"
![image](https://user-images.githubusercontent.com/36776278/180886481-ae6d1456-86f3-4c0e-acf4-bfb403086ce7.png)

**Comment by haroldao** [comment]
Here's the error outputted in the terminal for the shorcode "image"
![image](https://user-images.githubusercontent.com/36776278/180886714-c10720ea-4c8e-41ff-b307-e5ab50b55266.png)

**Comment by lihbr** [comment]
Hey there, OK:

### Link not working

It looks like you're using version 0.2.0 so the doc for the link component that applies to you is available here: https://github.com/prismicio-community/eleventy-plugin-prismic/blob/5d3910fc06d3aafd7ef8db7b939bff98bb96d469/DOCUMENTATION.md#link-paired-shortcode

But long story short, you can make it work by providing the `page` to the shortcode:

```njk
<ul>
	{% for alternateDocument in document.alternate_languages %}
	<li>
		{% link page, alternateDocument %}
		{{ alternateDocument.lang }}
		{% endlink %}
	</li>
	{% endfor %}
</ul>
```

In version 1.0.0 (beta), providing the `page` is not needed anymore so the previous version is meant to work with it.

### Image not working

This one is a bit trickier; because you're using the shortcode on a layout it basically tries to run it for every page. However, it appears some of your pages doesn't have a `footer_logo` image available, you can fix it this way by checking for its availability:

```njk
{% if document.data.footer_logo %}
	{% image document.data.footer_logo %}
{% endif %}
```

Although I assume you'd like the footer logo to be available globally, in such case you can access your layout directly this way:

```njk
{% image prismic.layout.en[0].data.footer_logo %}
```

(you can declare `layout` a singleton in your plugin config, if it's one, to avoid having the `[0]` accessor)

Let me know 💐

**Comment by haroldao** [comment]
I was using version 0.2.1 and the image was working after your comment but not the link issue. I updated to the latest release (v1 Beta 5) and now everything work fine !🍾🤩🚀
